//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ProtecTelegram.DataLayer.Database
{

	public partial class TeleGramUserRel : XPLiteObject
	{
		long fIdTelegram;
		[Key]
		public long IdTelegram
		{
			get { return fIdTelegram; }
			set { SetPropertyValue<long>(nameof(IdTelegram), ref fIdTelegram, value); }
		}
		string fUsername;
		[Indexed(Name = @"TeleGramUserRel_Username_Index")]
		public string Username
		{
			get { return fUsername; }
			set { SetPropertyValue<string>(nameof(Username), ref fUsername, value); }
		}
		DateTime fDateAdded;
		public DateTime DateAdded
		{
			get { return fDateAdded; }
			set { SetPropertyValue<DateTime>(nameof(DateAdded), ref fDateAdded, value); }
		}
		bool fActive;
		public bool Active
		{
			get { return fActive; }
			set { SetPropertyValue<bool>(nameof(Active), ref fActive, value); }
		}
	}

}
