//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ProtecTelegram.DataLayer.Database
{

	public partial class TeleGramInvitations : XPLiteObject
	{
		string fUsername;
		[Key]
		public string Username
		{
			get { return fUsername; }
			set { SetPropertyValue<string>(nameof(Username), ref fUsername, value); }
		}
		Guid fToken;
		public Guid Token
		{
			get { return fToken; }
			set { SetPropertyValue<Guid>(nameof(Token), ref fToken, value); }
		}
		DateTime fCreationDate;
		public DateTime CreationDate
		{
			get { return fCreationDate; }
			set { SetPropertyValue<DateTime>(nameof(CreationDate), ref fCreationDate, value); }
		}
		DateTime fExpirationDate;
		public DateTime ExpirationDate
		{
			get { return fExpirationDate; }
			set { SetPropertyValue<DateTime>(nameof(ExpirationDate), ref fExpirationDate, value); }
		}
	}

}
